services:
  app:
    build:
      args:
        - APP_USER_UID=${APP_USER_UID}
        - APP_GROUP_GID=${APP_GROUP_GID}
    volumes:
      - ./app:/usr/src/app
      - gems:/usr/local/bundle
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:107.0
    shm_size: 2gb
    ports:
      - "0.0.0.0:7900:7900"

volumes:
  gems:
