version: '3.7'

services:
  rails:
    build:
      context: ./rails
      additional_contexts:
        - scripts=./scripts
      dockerfile: ../Dockerfile.rails-dev
    tty: true
    env_file: .env
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
